export function MetaText() {
  return (
    <div className="container mx-auto pt-[50px] pb-[16px]">
      <p className="text-[12px] text-center">
        *VALID ON SELECT STYLES. ITEMS AS MARKED. NOT VALID WITH ANY OTHER OFFER. NOT VALID ON PREVIOUS PURCHASES. VALID FOR LIMITED TIME ONLY. *10% off PICKUP ORDERS NOT VALID WITH: BIRKENSTOCK, CHUBBIES, DICKIES, EDIKTED, FREE PEOPLE, HERSCHEL SUPPLY CO., JANSPORT, LEVI'S, NIKE, NIKE SB, RAINBOW SANDALS, STANLEY, STEVE MADDEN AND THE NORTH FACE MERCHANDISE.
      </p>
    </div>
  );
}